version: '3.7'
services:
  db:
    image: mysql:5.7
    ports:
      - "3336:3306"
    volumes:
      - ./local/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
